---
version: 2.1

executors:
    py-builder:
        docker:
            - image: circleci/python:3.8.5

commands:
    init-poetry:
        description: Checkout, install or load Poetry env, and cache on change.
        steps:
            - restore_cache:
                  keys:
                      - lock-{{ checksum "poetry.lock" }}
            - run: poetry install
            - save_cache:
                  key: lock-{{ checksum "poetry.lock" }}
                  paths:
                      - /home/circleci/.cache/pypoetry/virtualenvs

jobs:
    lint:
        executor: py-builder
        steps:
            - checkout
            - init-poetry
            - run: poetry run flake8
    test:
        executor: py-builder
        steps:
            - checkout
            - init-poetry
            - run: poetry run pytest --junitxml="test-results/integration/results.xml" tests/integration/
            - store_test_results:
                  path: test-results



workflows:
    default:
        jobs:
            - lint
            - test
